use_frameworks!

platform :ios, '8.0'

target 'UBShareKit_Example' do
  pod 'UBShareKit', :path => '../'
  pod 'UBShareActivities/Wechat',:git => 'https://github.com/Crazysiri/UBShareActivities.git'

  target 'UBShareKit_Tests' do
    inherit! :search_paths
    
  end
  pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  end
end
